### ISSUE TITLE
Change password settings

### ISSUE THREAD

**Issue by nostrband** [nostrband/noauth#143]
In ModalSettings, rename Cloud Sync section to Password, if not 'synced' then show 'Set password' button, 'Not set' red warning, and 'Please specify password to enable key export and to safely sync keys to other devices' text under button. If 'synced' then show 'Change password' button, green 'Enabled' label with a check, and empty text under button.

Set password and change password open another ModalPassword, with password and password confirmation inputs, and 'existing password' for change password mode. On 'save' button click 'saveKey' is called, with existing password as third param.

**Comment by bekbolsun22** [comment]
added!
