### ISSUE TITLE
Group apps by url on keys page 

### ISSUE THREAD

**Issue by brugeman** [nostrband/noauth#163]
Group apps by url (if url != ''), we will show 1 row per group. If group size == 1 then show the same record as today - icon, name, perms and last_active date time (remove npub). If group size > 1 then show icon, name, 'N connections' instead of perms (N - size of group) and last_active date time, and a V button at the right. 

Click on V button of a group drops down the list of apps of this group under the group row - same rows as today, but with left padding of 0.5em. Another clicks hides the apps of the group.

Last_active=latest record for this appNpub+npub from 'history' table, for group - max(last_active) of all apps in the group. 

Sort groups by name, sort apps in the group by last_active.

**Comment by brugeman** [comment]
Also sort groups by name, sort apps in the group by last_active.

**Comment by bekbolsun22** [comment]
added!
