### ISSUE TITLE
`Empty response` when trying to sign event

### ISSUE THREAD

**Issue by yukibtc** [nostrband/noauth#174]
Hi, I'm testing https://nsec.app and I'm receiving this error when trying to sign an event: "Empty response".

### To reproduce

Message request:

```json
{"id":"2391621581","method":"sign_event","params":[{"id":"238c8cc50d7294ef36578a9fe4189da71a593b8cf3c57b52494aa9021b1f9db4","pubkey":"79dff8f82963424e0bb02708a22e44b4980893e3a4be0fa3cb60a43b946764e3","created_at":1710847303,"kind":1,"tags":[],"content":"Testing rust-nostr NIP46 signer [bunker]"}]}
```

Signer secret key used in `nsec.app`: `nsec1ufnus6pju578ste3v90xd5m2decpuzpql2295m3sknqcjzyys9ls0qlc85`

**Comment by nostrband** [comment]
Params should contain an array of strings, please do JSON.stringify on your to-be-signed event.
