### ISSUE TITLE
Add 'Advanced options' section to ModalConnectApp (subNpub)

### ISSUE THREAD

**Issue by nostrband** [nostrband/noauth#190]
Advanced options button under the 'bunker url' input. When Advanced options clicked, a new section drops down with a 'Shared access' input (subNpub).

If subNpub is specified, must re-call the 'getConnectToken(npub, subNpub)' (each subNpub gets their own token). Then if the bunker url is used to sign into some app, that app will have the subNpub field equal to the one specified for this token (try on habla.news).

**Comment by nostrband** [comment]
Also, ModalConfirmConnect should show the subNpub from the req params. A new grey box under the app npub, with subNpub profile avatar and their npub/profile.name (just show npub and default avatar for now).

**Comment by nostrband** [comment]
First fix this: https://github.com/nostrband/noauth/issues/193 otherwise we'll be adding even more query string params to the modal, which are supposed to be removed.

**Comment by nostrband** [comment]
Also allow setting subNpub in App settings! This is even simpler!

**Comment by bekbolsun22** [comment]
Done!
