### ISSUE TITLE
Add subNpub to App Details modal

### ISSUE THREAD

**Issue by nostrband** [nostrband/noauth#197]
On App details, add 'Shared access with' input, with 'npub...' placeholder, this value is written to 'subNpub' field of 'app' object to db.  This means that this connection is created for another user to share access with them to our keys.

On KeyPage, look at all apps, find ones with non-empty subNpub field. If there are ones with non-empty subNpub, we add a dropdown at the top of Connected apps section. Dropdown contains "My connections" - selected by default, and then all unique subNpubs collected from all apps (with an Avatar - will load avatar and username them later, show default avatar and npub now).

If My connections is chosen - apps with empty subNpub are shown. If subNpub is chosen, &subNpub=xxx is added to query string and only apps with selected subNpub are shown.

Also, ModalConfirmEvent should show the subNpub from the app object. If subNpub is not empty, show a new grey box under the app npub, titled as "Shared access with" with subNpub profile avatar and their npub/profile.name (just show subNpub and default avatar for now).

**Comment by bekbolsun22** [comment]
Done!
