### ISSUE TITLE
Group app perms w/ same domain

### ISSUE THREAD

**Issue by nostrband** [nostrband/noauth#55]
In ConfirmConnect, find all existing apps that have the same appDomain.

Find all perms of all existing apps with same domain, make a unique list of existing perms.

If there are existing perms for this appDomain, show another ACTION_TYPE.REUSE button to the right of REQUESTED/BASIC (so two buttons - reuse and the one shown now).

Clicking REUSE should fill the state variable 'perms' with the existing perms for this appDomain. Clicking the other button fills with corresponding perms.

**Comment by nostrband** [comment]
But keep various connection settings separate, like duration of connection, 2fa settings etc

**Comment by bekbolsun22** [comment]
Done!
